-- Upgrade script from ART 3.7 to ART 3.8

-- CHANGES:
-- update database version
-- make some varchar columns nullable

-- ------------------------------------------------


-- update database version
UPDATE ART_DATABASE_VERSION SET DATABASE_VERSION='3.8-snapshot';

-- make some varchar columns nullable
ALTER TABLE ART_QUERY_GROUPS ADD DESCRIPTION_TEMP VARCHAR(200);
UPDATE ART_QUERY_GROUPS SET DESCRIPTION_TEMP=DESCRIPTION;
ALTER TABLE ART_QUERY_GROUPS DROP COLUMN DESCRIPTION;
ALTER TABLE ART_QUERY_GROUPS ADD DESCRIPTION VARCHAR(200);
UPDATE ART_QUERY_GROUPS SET DESCRIPTION=DESCRIPTION_TEMP;
ALTER TABLE ART_QUERY_GROUPS DROP COLUMN DESCRIPTION_TEMP;
