/**
 * Copyright (C) 2014 Enrico Liboni <eliboni@users.sourceforge.net>
 *
 * This file is part of ART.
 *
 * ART is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, version 2 of the License.
 *
 * ART is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * ART. If not, see <http://www.gnu.org/licenses/>.
 */
package art.settings;

/**
 * Class to represent custom settings that can't be set from the user interface.
 * Mainly to enhance security.
 *
 * @author Timothy Anyona
 */
public class CustomSettings {

	private boolean showErrors = true; //whether exception details are shown in the user interface
	private boolean enableDirectParameterSubstitution; //whether direct parameter values in report sql is enabled - instead of using preparedstatements
	private String customExportPath; //custom path for export files i.e. for files generated by interactive queries and jobs

	/**
	 * @return the showErrors
	 */
	public boolean isShowErrors() {
		return showErrors;
	}

	/**
	 * @param showErrors the showErrors to set
	 */
	public void setShowErrors(boolean showErrors) {
		this.showErrors = showErrors;
	}

	/**
	 * @return the enableDirectParameterSubstitution
	 */
	public boolean isEnableDirectParameterSubstitution() {
		return enableDirectParameterSubstitution;
	}

	/**
	 * @param enableDirectParameterSubstitution the
	 * enableDirectParameterSubstitution to set
	 */
	public void setEnableDirectParameterSubstitution(boolean enableDirectParameterSubstitution) {
		this.enableDirectParameterSubstitution = enableDirectParameterSubstitution;
	}

	/**
	 * @return the customExportPath
	 */
	public String getCustomExportPath() {
		return customExportPath;
	}

	/**
	 * @param customExportPath the customExportPath to set
	 */
	public void setCustomExportPath(String customExportPath) {
		this.customExportPath = customExportPath;
	}

}
