-- Add indexes to ART database tables

CREATE INDEX asp_ix_uid_rid ON ART_SAVED_PARAMETERS(USER_ID, REPORT_ID);
CREATE INDEX ajp_ix_jid ON ART_JOBS_PARAMETERS(JOB_ID);
CREATE INDEX al_ix_dt ON ART_LOGS(LOG_DATE);
CREATE INDEX al_ix_unm ON ART_LOGS(USERNAME);
CREATE INDEX al_ix_tp ON ART_LOGS(LOG_TYPE);
CREATE INDEX al_ix_qid ON ART_LOGS(QUERY_ID;
CREATE INDEX al_ix_tt ON ART_LOGS(TOTAL_TIME);