-- Add indexes to ART database tables

CREATE INDEX art_svpmt_ix_uid_rid ON ART_SAVED_PARAMETERS(USER_ID, REPORT_ID);
CREATE INDEX art_jbpmt_ix_jid ON ART_JOBS_PARAMETERS(JOB_ID);
CREATE INDEX art_lg_ix_dt ON ART_LOGS(LOG_DATE);
CREATE INDEX art_lg_ix_unm ON ART_LOGS(USERNAME);
CREATE INDEX art_lg_ix_tp ON ART_LOGS(LOG_TYPE);
CREATE INDEX art_lg_ix_iid ON ART_LOGS(ITEM_ID);
CREATE INDEX art_lg_ix_tt ON ART_LOGS(TOTAL_TIME);
CREATE INDEX art_upardf_ix_pdk ON ART_USER_PARAM_DEFAULTS(PARAM_DEFAULT_KEY);
CREATE INDEX art_upardf_ix_uid_pid ON ART_USER_PARAM_DEFAULTS(USER_ID, PARAMETER_ID);
CREATE INDEX art_upardf_ix_pid ON ART_USER_PARAM_DEFAULTS(PARAMETER_ID);
CREATE INDEX art_ugpardf_ix_pdk ON ART_USER_GROUP_PARAM_DEFAULTS(PARAM_DEFAULT_KEY);
CREATE INDEX art_ugpardf_ix_ugid_pid ON ART_USER_GROUP_PARAM_DEFAULTS(USER_GROUP_ID, PARAMETER_ID);
CREATE INDEX art_ugpardf_ix_pid ON ART_USER_GROUP_PARAM_DEFAULTS(PARAMETER_ID);
CREATE INDEX art_urul_ix_rvk ON ART_USER_RULES(RULE_VALUE_KEY);
CREATE INDEX art_urul_ix_uid_rid_rv ON ART_USER_RULES(USER_ID, RULE_ID, RULE_VALUE);
CREATE INDEX art_urul_ix_rid ON ART_USER_RULES(RULE_ID);
CREATE INDEX art_ugrul_ix_rvk ON ART_USER_GROUP_RULES(RULE_VALUE_KEY);
CREATE INDEX art_ugrul_ix_ugid_rid_rv ON ART_USER_GROUP_RULES(USER_GROUP_ID, RULE_ID, RULE_VALUE);
CREATE INDEX art_ugrul_ix_rid ON ART_USER_GROUP_RULES(RULE_ID);
CREATE INDEX art_ufxparvl_ix_fvk ON ART_USER_FIXED_PARAM_VAL(FIXED_VALUE_KEY);
CREATE INDEX art_ufxparvl_ix_uid_pid ON ART_USER_FIXED_PARAM_VAL(USER_ID, PARAMETER_ID);
CREATE INDEX art_ufxparvl_ix_pid ON ART_USER_FIXED_PARAM_VAL(PARAMETER_ID);
CREATE INDEX art_ugfxparvl_ix_fvk ON ART_USER_GROUP_FIXED_PARAM_VAL(FIXED_VALUE_KEY);
CREATE INDEX art_ugfxparvl_ix_ugid_pid ON ART_USER_GROUP_FIXED_PARAM_VAL(USER_GROUP_ID, PARAMETER_ID);
CREATE INDEX art_ugfxparvl_ix_pid ON ART_USER_GROUP_FIXED_PARAM_VAL(PARAMETER_ID);
