-- Add foreign keys to ART database tables

ALTER TABLE ART_QUERIES ADD CONSTRAINT aq_fk_ds_id FOREIGN KEY(DATASOURCE_ID) REFERENCES ART_DATABASES(DATABASE_ID);
ALTER TABLE ART_USERS ADD CONSTRAINT au_fk_acc_lvl FOREIGN KEY(ACCESS_LEVEL) REFERENCES ART_ACCESS_LEVELS(ACCESS_LEVEL);
