-- Drop ART database tables

-- drop quartz tables
DROP TABLE QRTZ_FIRED_TRIGGERS;
DROP TABLE QRTZ_PAUSED_TRIGGER_GRPS;
DROP TABLE QRTZ_SCHEDULER_STATE;
DROP TABLE QRTZ_LOCKS;
DROP TABLE QRTZ_SIMPLE_TRIGGERS;
DROP TABLE QRTZ_SIMPROP_TRIGGERS;
DROP TABLE QRTZ_CRON_TRIGGERS;
DROP TABLE QRTZ_BLOB_TRIGGERS;
DROP TABLE QRTZ_TRIGGERS;
DROP TABLE QRTZ_JOB_DETAILS;
DROP TABLE QRTZ_CALENDARS;

-- drop art tables
DROP TABLE ART_USER_GROUP_ASSIGNMENT;
DROP TABLE ART_USER_GROUP_RULES;
DROP TABLE ART_USER_JOBS;
DROP TABLE ART_USER_GROUP_QUERIES;
DROP TABLE ART_USER_GROUP_GROUPS;
DROP TABLE ART_USER_GROUP_JOBS;
DROP TABLE ART_USER_GROUPS;
DROP TABLE ART_QUERIES;
DROP TABLE ART_USERS;
DROP TABLE ART_DATABASES;
DROP TABLE ART_ACCESS_LEVELS;
DROP TABLE ART_QUERY_GROUPS;
DROP TABLE ART_CUSTOM_UPGRADES
DROP TABLE ART_DATABASE_VERSION;
