-- Drop foreign keys from ART database tables

-- NOTES:
-- for mysql, replace DROP CONSTRAINT with DROP FOREIGN KEY

-- ------------------------

ALTER TABLE ART_USERS DROP CONSTRAINT au_fk_acc_lvl;
ALTER TABLE ART_USERS DROP CONSTRAINT au_fk_def_qr_grp;
ALTER TABLE ART_USER_GROUPS DROP CONSTRAINT aug_fk_dqg;
ALTER TABLE ART_USER_USERGROUP_MAP DROP CONSTRAINT art_uugm_fk_ug_id;
ALTER TABLE ART_USER_USERGROUP_MAP DROP CONSTRAINT art_uugm_fk_u_id;
ALTER TABLE ART_QUERIES DROP CONSTRAINT aq_fk_qt;
ALTER TABLE ART_QUERIES DROP CONSTRAINT aq_fk_ds_id;
ALTER TABLE ART_QUERIES DROP CONSTRAINT aq_fk_enc_id;
ALTER TABLE ART_REPORT_REPORT_GROUPS DROP CONSTRAINT arrg_fk_r_id;
ALTER TABLE ART_REPORT_REPORT_GROUPS DROP CONSTRAINT arrg_fk_rg_id;
ALTER TABLE ART_ADMIN_PRIVILEGES DROP CONSTRAINT aap_fk_u_id;
ALTER TABLE ART_USER_REPORT_MAP DROP CONSTRAINT art_urm_fk_u_id;
ALTER TABLE ART_USER_REPORT_MAP DROP CONSTRAINT art_urm_fk_r_id;
ALTER TABLE ART_USER_REPORTGROUP_MAP DROP CONSTRAINT art_urgm_fk_u_id;
ALTER TABLE ART_USER_REPORTGROUP_MAP DROP CONSTRAINT art_urgm_fk_rg_id;
ALTER TABLE ART_PARAMETERS DROP CONSTRAINT ap_fk_dv_rid;
ALTER TABLE ART_PARAMETERS DROP CONSTRAINT ap_fk_lov_rid;
ALTER TABLE ART_REPORT_PARAMETERS DROP CONSTRAINT arp_fk_rid;
ALTER TABLE ART_REPORT_PARAMETERS DROP CONSTRAINT arp_fk_p_id;
ALTER TABLE ART_QUERY_RULES DROP CONSTRAINT aqr_fk_q_id;
ALTER TABLE ART_QUERY_RULES DROP CONSTRAINT aqr_fk_r_id;
ALTER TABLE ART_USER_RULES DROP CONSTRAINT aur_fk_u_id;
ALTER TABLE ART_USER_RULES DROP CONSTRAINT aur_fk_r_id;
ALTER TABLE ART_USER_GROUP_RULES DROP CONSTRAINT augr_fk_ug_id;
ALTER TABLE ART_USER_GROUP_RULES DROP CONSTRAINT augr_fk_r_id;
ALTER TABLE ART_JOBS DROP CONSTRAINT aj_fk_q_id;
ALTER TABLE ART_JOBS DROP CONSTRAINT aj_fk_u_id;
ALTER TABLE ART_JOBS DROP CONSTRAINT aj_fk_r_q_id;
ALTER TABLE ART_JOBS DROP CONSTRAINT aj_fk_s_id;
ALTER TABLE ART_JOBS DROP CONSTRAINT aj_fk_ss_id;
ALTER TABLE ART_JOBS_PARAMETERS DROP CONSTRAINT ajp_fk_j_id;
ALTER TABLE ART_USER_JOB_MAP DROP CONSTRAINT art_ujm_fk_j_id;
ALTER TABLE ART_USER_JOB_MAP DROP CONSTRAINT art_ujm_fk_u_id;
ALTER TABLE ART_USER_JOB_MAP DROP CONSTRAINT art_ujm_fk_ug_id;
ALTER TABLE ART_USER_GROUP_QUERIES DROP CONSTRAINT augq_fk_ug_id;
ALTER TABLE ART_USER_GROUP_QUERIES DROP CONSTRAINT augq_fk_q_id;
ALTER TABLE ART_USER_GROUP_GROUPS DROP CONSTRAINT augg_fk_ug_id;
ALTER TABLE ART_USER_GROUP_GROUPS DROP CONSTRAINT augg_fk_qg_id;
ALTER TABLE ART_USER_GROUP_JOBS DROP CONSTRAINT augj_fk_ug_id;
ALTER TABLE ART_USER_GROUP_JOBS DROP CONSTRAINT augj_fk_j_id;
ALTER TABLE ART_DRILLDOWN_QUERIES DROP CONSTRAINT adq_fk_q_id;
ALTER TABLE ART_DRILLDOWN_QUERIES DROP CONSTRAINT adq_fk_dq_id;
ALTER TABLE ART_JOB_ARCHIVES DROP CONSTRAINT aja_fk_j_id;
ALTER TABLE ART_JOB_ARCHIVES DROP CONSTRAINT aja_fk_u_id;
ALTER TABLE ART_LOGGED_IN_USERS DROP CONSTRAINT alu_fk_u_id;
ALTER TABLE ART_SCHEDULE_HOLIDAY_MAP DROP CONSTRAINT ashm_fk_s_id;
ALTER TABLE ART_SCHEDULE_HOLIDAY_MAP DROP CONSTRAINT ashm_fk_h_id;
ALTER TABLE ART_JOB_HOLIDAY_MAP DROP CONSTRAINT ajhm_fk_j_id;
ALTER TABLE ART_JOB_HOLIDAY_MAP DROP CONSTRAINT ajhm_fk_h_id;
ALTER TABLE ART_JOB_DESTINATION_MAP DROP CONSTRAINT ajdm_fk_j_id;
ALTER TABLE ART_JOB_DESTINATION_MAP DROP CONSTRAINT ajdm_fk_d_id;
ALTER TABLE ART_SAVED_PARAMETERS DROP CONSTRAINT asp_fk_u_id;
ALTER TABLE ART_SAVED_PARAMETERS DROP CONSTRAINT asp_fk_r_id;
ALTER TABLE ART_USER_PARAM_DEFAULTS DROP CONSTRAINT aupd_fk_u_id;
ALTER TABLE ART_USER_PARAM_DEFAULTS DROP CONSTRAINT aupd_fk_p_id;
ALTER TABLE ART_USER_GROUP_PARAM_DEFAULTS DROP CONSTRAINT augpd_fk_ug_id;
ALTER TABLE ART_USER_GROUP_PARAM_DEFAULTS DROP CONSTRAINT augpd_fk_p_id;
ALTER TABLE ART_USER_FIXED_PARAM_VAL DROP CONSTRAINT aufpv_fk_u_id;
ALTER TABLE ART_USER_FIXED_PARAM_VAL DROP CONSTRAINT aufpv_fk_p_id;
ALTER TABLE ART_USER_GROUP_FIXED_PARAM_VAL DROP CONSTRAINT augfpv_fk_ug_id;
ALTER TABLE ART_USER_GROUP_FIXED_PARAM_VAL DROP CONSTRAINT augfpv_fk_p_id;
ALTER TABLE ART_ROLE_PERMISSION_MAP DROP CONSTRAINT art_rpm_fk_r_id;
ALTER TABLE ART_ROLE_PERMISSION_MAP DROP CONSTRAINT art_rpm_fk_p_id;
ALTER TABLE ART_USER_ROLE_MAP DROP CONSTRAINT art_urm_fk_u_id;
ALTER TABLE ART_USER_ROLE_MAP DROP CONSTRAINT art_urm_fk_r_id;
ALTER TABLE ART_USER_GROUP_ROLE_MAP DROP CONSTRAINT art_ugrm_fk_ug_id;
ALTER TABLE ART_USER_GROUP_ROLE_MAP DROP CONSTRAINT art_ugrm_fk_r_id;
ALTER TABLE ART_USER_PERMISSION_MAP DROP CONSTRAINT art_upm_fk_u_id;
ALTER TABLE ART_USER_PERMISSION_MAP DROP CONSTRAINT art_upm_fk_p_id;
ALTER TABLE ART_USER_GROUP_PERM_MAP DROP CONSTRAINT art_ugpm_fk_ug_id;
ALTER TABLE ART_USER_GROUP_PERM_MAP DROP CONSTRAINT art_ugpm_fk_p_id;
